module.exports = {
  title:'Welcome!',
  content:[
    {
        type:'markdown',
        markdown:"# Welcome to WebBuilder!\n## Title 1\n Image:![{round}Image of Yaktocat](https://cloud.githubusercontent.com/assets/1424573/4785631/dc5ddcd2-5d82-11e4-88a2-06fdabbe4fb8.png) bla bla bla\n![Image of Yaktocat](https://cloud.githubusercontent.com/assets/1424573/4785631/dc5ddcd2-5d82-11e4-88a2-06fdabbe4fb8.png)\n",
    },
    {
        type:'form',
        method:'get',
        action:'submit.html',
        content:[
            {
                type:'fieldset',
                label:'Hello !',
                content:[
                    {
                        type:'button',
                        label:'hey',
                    },
                    {
                        type:'rating',
                        rating:5,
                        value:4,
                        label:'Rate this site:',
                        name:'SiteRate',
                    },
                    {
                        type:'hr',
                    },
                    {
                        type:'buttonGroup',
                        content:[
                            {
                                type:'button',
                                reset:true,
                                label:'reset',
                            },
                            {
                                type:'button',
                                submit:true,
                                label:'submit',
                            }
                        ],
                    }
                ],
            }
        ],
    },
    {
        type:'button',
        label:'hey!',
    },
  ],
};
